export const todoActionTypes = {
  TODO_ADD_ITEM: "TODO:ADD_ITEM",
  TODO_ADD_ITEMS: "TODO:ADD_ITEMS",
  TODO_TOGGLE: "TODO:TOGGLE",
  TODO_REMOVE: "TODO:REMOVE",
  TODO_REMOVE_ALL: "TODO:REMOVE_ALL"
};
